// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO26Fcb875-0KPdghHxpB1nS5-JLjsMao',
    appId: '1:640890471727:web:a1ebd971f65964abbb0dda',
    messagingSenderId: '640890471727',
    projectId: 'sudokusolver-3928d',
    authDomain: 'sudokusolver-3928d.firebaseapp.com',
    storageBucket: 'sudokusolver-3928d.firebasestorage.app',
    measurementId: 'G-99030H66CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyfSaO0Vr1y3MEyr_N8_Vk_NHU15LUbk',
    appId: '1:640890471727:android:0323930890c88d37bb0dda',
    messagingSenderId: '640890471727',
    projectId: 'sudokusolver-3928d',
    storageBucket: 'sudokusolver-3928d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfx-SyGRs5MUkpwpc-2q1RzrMOOKjWXQ',
    appId: '1:640890471727:ios:2fc67b0a67ad1058bb0dda',
    messagingSenderId: '640890471727',
    projectId: 'sudokusolver-3928d',
    storageBucket: 'sudokusolver-3928d.firebasestorage.app',
    androidClientId: '640890471727-tgan7svepmi8kdd5rpnb22vfi2g51ibn.apps.googleusercontent.com',
    iosClientId: '640890471727-ck4uuhu79g51m376pe5j8ojf18mugsq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfx-SyGRs5MUkpwpc-2q1RzrMOOKjWXQ',
    appId: '1:640890471727:ios:2fc67b0a67ad1058bb0dda',
    messagingSenderId: '640890471727',
    projectId: 'sudokusolver-3928d',
    storageBucket: 'sudokusolver-3928d.firebasestorage.app',
    androidClientId: '640890471727-tgan7svepmi8kdd5rpnb22vfi2g51ibn.apps.googleusercontent.com',
    iosClientId: '640890471727-ck4uuhu79g51m376pe5j8ojf18mugsq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO26Fcb875-0KPdghHxpB1nS5-JLjsMao',
    appId: '1:640890471727:web:d4e91eaf1f18bacdbb0dda',
    messagingSenderId: '640890471727',
    projectId: 'sudokusolver-3928d',
    authDomain: 'sudokusolver-3928d.firebaseapp.com',
    storageBucket: 'sudokusolver-3928d.firebasestorage.app',
    measurementId: 'G-116TCHZYGY',
  );
}
